### ISSUE TITLE
Not build with cmake on Mac ?

### ISSUE THREAD

**Issue by ray-x** [ltcmelo/uaiso#11]
brew install flex bison
git clone --recurse-submodules https://github.com/ltcmelo/uaiso.git
....
cd uaiso
cmake .

[  0%] Generating D/DLexer.h, D/DLexer.cpp, D/DParser.h, D/DParser.cpp, Go/GoLexer.h, Go/GoLexer.cpp, Go/GoParser.h, Go/GoParser.cpp, Ast/AstCast.h, Parsing/Token.h, Parsing/TokenName.cpp, TestDataAbsPath.txt
Generating tokens from Parsing/Tokens.def
Creating Parsing/Token.h
Creating Parsing/TokenName.cpp
Writing to D/D.y
Writing to Go/Go.y
Calling bison on D
D/D.y:33.9-18: syntax error, unexpected identifier, expecting string
Traceback (most recent call last):
  File "/Users/rayx/software/uaiso/Scripts/GenFlexBison.py", line 65, in <module>
    run()
  File "/Users/rayx/software/uaiso/Scripts/GenFlexBison.py", line 57, in run
    gen_parser("D")
  File "/Users/rayx/software/uaiso/Scripts/GenFlexBison.py", line 48, in gen_parser
    os.rename("%sParser.h" % lang, "%s/%sParser.h" % (lang, lang))
OSError: [Errno 2] No such file or directory
make[2]: *** [D/DLexer.h] Error 1
make[1]: *** [CMakeFiles/UaiSoEngine.dir/all] Error 2
make: *** [all] Error 2

**Comment by ltcmelo** [comment]
That might be caused due to incompatible bison versions. I was using Apple's port, if I'm not mistaken.

**Comment by ray-x** [comment]
You are correct. The system will pickup bison provided by Xcode by default. set PATH of brew Bison will fix this issue.
