### ISSUE TITLE
'YYID' was not declared in this scope (by msys)

### ISSUE THREAD

**Issue by gonboy** [ltcmelo/uaiso#2]
In file included from D/D.y:107:0:
DParser.cpp: In function 'YYRESULTTAG yyuserAction(yyRuleNum, size_t, yyGLRStackItem*, yyGLRStack*, D_YYSTYPE*, D_YYLTYPE*, yyscan_t, uaiso::DParsingContext*)':
D/D.y:80:18: error: 'YYID' was not declared in this scope
       if (YYID (N))                                                     \
                  ^
DParser.cpp:7430:3: note: in expansion of macro 'YYLLOC_DEFAULT'
D/D.y:96:19: error: 'YYID' was not declared in this scope
     while (YYID (0))
                   ^
DParser.cpp:7430:3: note: in expansion of macro 'YYLLOC_DEFAULT'
DParser.cpp: In function 'void yyresolveLocations(yyGLRState*, int, yyGLRStack*, yyscan_t, uaiso::DParsingContext*)':
D/D.y:80:18: error: 'YYID' was not declared in this scope
       if (YYID (N))                                                     \
                  ^
DParser.cpp:14242:13: note: in expansion of macro 'YYLLOC_DEFAULT'
D/D.y:96:19: error: 'YYID' was not declared in this scope
     while (YYID (0))
                   ^
DParser.cpp:14242:13: note: in expansion of macro 'YYLLOC_DEFAULT'
DParser.cpp: In function 'void yyrecoverSyntaxError(yyGLRStack*, yyscan_t, uaiso::DParsingContext*)':
D/D.y:80:18: error: 'YYID' was not declared in this scope
       if (YYID (N))                                                     \
                  ^
DParser.cpp:14665:13: note: in expansion of macro 'YYLLOC_DEFAULT'
D/D.y:96:19: error: 'YYID' was not declared in this scope
     while (YYID (0))
                   ^
DParser.cpp:14665:13: note: in expansion of macro 'YYLLOC_DEFAULT'
D/D.y:80:18: error: 'YYID' was not declared in this scope
       if (YYID (N))                                                     \
                  ^
DParser.cpp:14722:15: note: in expansion of macro 'YYLLOC_DEFAULT'
D/D.y:96:19: error: 'YYID' was not declared in this scope
     while (YYID (0))
                   ^
DParser.cpp:14722:15: note: in expansion of macro 'YYLLOC_DEFAULT'

**Comment by ltcmelo** [comment]
Hi gonboy, thanks for reporting this issue. I suspect this might be caused to slight variations across bison versions/platforms. I'm using 2.7.12, which one are you using?

**Comment by kai66673** [comment]
I confirm this. Downgrade bison to version 2.7.12 (ubuntu 14.04) fix the problem.

**Comment by gonboy** [comment]
the Latest version(2016-5-25 ), test OK.

**Comment by kubaroth** [comment]
Hi there, I'm still getting the very same error after bison downgrade on Mint 17.
flex 2.5.35
bison (GNU Bison) 2.7.12-4996

**Comment by ltcmelo** [comment]
Have you tried a clean build, from scratch? The current build script will only (re)generate the parsers if none are found. You might need to manually delete the old ones, if necessary.

**Comment by kubaroth** [comment]
right, thanks for pointing out - I was running make clean which didn't purge everything
