### ISSUE TITLE
make command Failed with following error

### ISSUE THREAD

**Issue by suyog44** [ltcmelo/uaiso#7]
/home/xxxx/uaiso/./Common/Test.h:28:32: fatal error: StringUtils/trim.hpp: No such file or directory
compilation terminated.
make[2]: *** [CMakeFiles/UaiSoEngine.dir/Ast/AstDecl.cpp.o] Error 1
make[1]: *** [CMakeFiles/UaiSoEngine.dir/all] Error 2
make: *** [all] Error 2

**Comment by ltcmelo** [comment]
File StringUtils/trim.hpp comes from a 3rd party library. If it's not there, one possible cause is that you didn't clone uaiso recursively.

**Comment by suyog44** [comment]
I upgraded gcc compiler to gcc-5 and problem solved. Thanks you so much sir. Great worlk

**Comment by ltcmelo** [comment]
You're welcome. Thanks for trying out the project.
