### ISSUE TITLE
Compilation Error in code

### ISSUE THREAD

**Issue by suyog44** [ltcmelo/uaiso#8]
/home/xxxx/uaiso/./Ast/AstName.h:37:16: error: ‘uaiso::Ast::Ast’ names constructor
/home/xxxx/uaiso/./Ast/AstName.h:40:17: warning: attributes ignored on elaborated-type-specifier that is not a forward declaration [-Wattributes]
/home/xxxx/uaiso/./Ast/AstName.h:40:36: error: expected initializer before ‘:’ token
/home/xxxx/uaiso/Ast/AstDecl.cpp:31:1: error: expected ‘}’ at end of input
make[2]: *** [CMakeFiles/UaiSoEngine.dir/Ast/AstDecl.cpp.o] Error 1
make[1]: *** [CMakeFiles/UaiSoEngine.dir/all] Error 2
make: *** [all] Error 2

**Comment by ltcmelo** [comment]
Could you please verify whether your compiler (version) is C++11 conformant? Uaiso requires C++14 actually.

**Comment by ltcmelo** [comment]
Since you mentioned in the other issue you upgraded the compiler and things worked I'm closing this.
